mkdir -p bundle
mkdir -p bundle/src
mkdir -p bundle/src/img
mkdir -p bundle/src/static
cp src/client.min.* bundle/src
cp src/img/exn64.png bundle/src/img
cp src/img/exn64.ico bundle/src/img
cp index.html bundle 
cp src/static/jsonlint.js bundle/src/static 
